name: Run Unit Tests on PR

on:
  pull_request:
    branches: [ master, staging, ci_testing ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101 
        
    - name: Restore Dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
      # set pr number, if it's a pr build
    - name: Set PR Build Number
      id: PRNUMBER
      if: ${{ github.event_name == 'pull_request' }}
      uses: kkak10/pr-number-action@v1.3

      # set report file and title 
    - name: Set Test Title
      run: | 
            if ${{ github.event_name == 'pull_request' }}
            then
              echo "run_title=Test_Run_for_PR_#${{steps.PRNUMBER.outputs.pr}}_(${{github.run_number}})" >> $GITHUB_ENV
              echo "file_name=TestReport_${{steps.PRNUMBER.outputs.pr}}_${{github.run_number}}"  >> $GITHUB_ENV
            else
              echo "run_title=Test_Run_${{github.run_number}}" >> $GITHUB_ENV
              echo "file_name=TestReport_${{github.run_number}}" >> $GITHUB_ENV
            fi
            
    - name: Test Api
      run: dotnet test --no-restore --no-build --logger:"liquid.md;LogFileName=${{github.workspace}}/${{env.file_name}}_Api.md;Title=${{env.run_title}}_Api;"

    # upload report as build artifact
    - name: Upload Api Test Report as a Build Artifact
      uses: actions/upload-artifact@v2
      if: ${{always()}}
      with:
        name: 'Api Test Run'
        path: "${{github.workspace}}/${{env.file_name}}_Api.md"

    - name: Comment Api Test Results on PR
      uses: machine-learning-apps/pr-comment@master
      if: ${{ github.event_name == 'pull_request' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        path: "${{ env.file_name }}_Api.md"
        
        
